services:
  - type: web
    name: file-converter
    runtime: docker
    region: frankfurt
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
      cd ../backend
      ./gradlew build
    startCommand: ""
    autoDeploy: true
    rootDir: backend
